# Generated by Django 6.1.1 on 2026-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('customer', 'customer'), ('seller', 'seller'), ('admin', 'admin')], default='customer', max_length=20)),
            ],
        ),
    ]
